<?php

namespace Database\Factories;

use App\Enums\ContentSource;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Story>
 */
class StoryFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'title_zh' => fake()->sentence(3),
            'title_pinyin' => fake()->sentence(3),
            'title_id' => fake()->sentence(3),
            'slug' => fake()->unique()->slug(),
            'description_id' => fake()->paragraph(),
            'hsk_level' => fake()->numberBetween(1, 6),
            'difficulty_score' => fake()->randomFloat(2, 1, 6),
            'word_count' => fake()->numberBetween(50, 500),
            'unique_word_count' => fake()->numberBetween(20, 200),
            'sentence_count' => fake()->numberBetween(5, 50),
            'estimated_minutes' => fake()->numberBetween(2, 15),
            'thumbnail_url' => null,
            'is_premium' => false,
            'is_published' => true,
            'published_at' => now(),
            'content_source' => ContentSource::Manual,
            'created_by' => null,
        ];
    }

    /**
     * Indicate that the story is premium.
     */
    public function premium(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_premium' => true,
        ]);
    }

    /**
     * Indicate that the story is a draft.
     */
    public function draft(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_published' => false,
            'published_at' => null,
        ]);
    }

    /**
     * Indicate that the story was generated by AI.
     */
    public function aiGenerated(): static
    {
        return $this->state(fn (array $attributes) => [
            'content_source' => ContentSource::AiGenerated,
        ]);
    }
}
